name: pdi-topics
channels:
- conda-forge
- vida-nyu
dependencies:
- python=3.5.5
- pip=18.0
- scikit-learn=0.19.0
- bokeh=0.13.0
- numpy=1.13.1
- nltk=3.2.5=py_0
- jupyter=1.0.0=py35_0
- gensim=3.2.0=py35_0
- scattertext
- pandas=0.23.4
- spacy=2.0.11
- elasticsearch=6.3.0
- elasticsearch-dsl=6.1.0
- pdfminer.six=20170720
- wordcloud
- matplotlib
- line_profiler
- pillow=4.3.0
- vida-nyu::pyldavis=2.1.0=py35_0
